name: Test Workflow

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Get Changed Files
        id: changed
        uses: citrix-workspace/g11n-mas-test@master
        with:
          paths: ^main.js

      - name: Echo Match
        if: steps.changed.outputs.matched == 'true'
        run: echo Matched
